# TensorFlow and Keras

Tensorflow is a Deep Learning and Neural Networks Library that can be used to solve machine learning and deep learning problems and provides efficient tools to implement various algorithms

Keras is a high-level API that runs on top of tensorflow

# TensorFlow - Tensor Basics

This Notebook contains the basics and building blocks of tensorflow that are Tensors which are simply n-dimensional arrays



In [1]:
#importing the libraries
import tensorflow as tf
import numpy as np

# Scalar, Vectors and Matrices

scalars are 0 dimensional tensors,
vectors are 1 dimensional tensors
and matrices are multi-dimensional tensors

Scalars, Vectors and Matrices can be created in tensorflow with the function constant

In [2]:
#scalars in tensorflow
a = tf.constant(1)
a.numpy()

1

In [3]:
#vectors in tensorflow
list1 = [1,2,3,4,5]
arr1 = np.array([6,7,82,4,7])
tensor1 = tf.constant(list1,dtype=tf.int64)
tensor2 = tf.constant(arr1,tf.int64)
print(tensor1.numpy(),"\n",tensor2.numpy())

[1 2 3 4 5] 
 [ 6  7 82  4  7]


In [4]:
#matrices in tensrorflow
mat1 = tf.constant([[1,2,3],
                    [4,5,6],
                    [7,8,9]])
mat1.numpy()

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

# Arithemetic operations on tensors

In [5]:
#tensor operations
print((tensor1 + tensor2).numpy())
print((tensor1 - tensor2).numpy())
print((tensor1 * tensor2).numpy())
print((tensor1 / tensor2).numpy())

[ 7  9 85  8 12]
[ -5  -5 -79   0  -2]
[  6  14 246  16  35]
[0.16666667 0.28571429 0.03658537 1.         0.71428571]


# Broadcasting in tensorflow

Broadcasting allows the interaction between tensors of multiple sizes.

For more details on broadcasting , refer to the pytorch course 

In [6]:
#broadcasting 
print(mat1 + 5,"\n\n")
print(mat1 + [2,3,4])

tf.Tensor(
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]], shape=(3, 3), dtype=int32) 


tf.Tensor(
[[ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]], shape=(3, 3), dtype=int32)
